export const PODCAST_API = {
  URL: "podcast",
  SEARCH_URL: "/search",
  EPISODE_DETAILS: "/episodes/{id}",
  PODCAST_DETAILS: "/detail",
  PODCAST_EPISODES: "/episodes",
  GENRES_URL: "/genres",
  CREATOR_PODCASTS: "/creator",
  ADMIN_URL: "/admin",
  CREATE_PODCAST: "/create",
  DELETE_PODCAST: "/{podcastId}/delete",
  UPDATE_PODCAST: "/update",
  CREATE_EPISODE: "/episode/add",
  DELETE_EPISODE: "/{podcastId}/episode/{episodeId}",
  UPDATE_EPISODE: "/episode/update",
}
